
# SEO settings
title: "yellow"
title2: "'s blog" # default: ""
description: "做一些技术笔记、分享和讨论"
keywords: "java, web, hadoop, spark"
url: https://mtide.net # site url
baseurl: "/" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

repo: https://github.com/mtide/mtide.github.io
comments: true

# Build settings
permalink   : /:categories/:title.html
markdown    : kramdown
highlighter : rouge
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: false

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "mtide.net"
  job      : "码农"
  bio      : "yellow，目前正在做自己喜欢的事。<br>关注互联网产品，喜欢极致和偏执的东西。"
  thumb    : /images/author.jpg
  email    : mtide@qq.com
  url      : https://mtide.net
  github   : https://github.com/mtide

# social settings
og_locale: "zh_CN"

gems:
  - bourbon
  - jekyll-paginate

paginate: 20

# navbar pages
navbar:
  - slug : WEB
    title: WEB
  - slug : JAVA
    title: JAVA
  - slug : BIGDATA
    title: BIGDATA
  - slug : NOTE
    title: NOTE

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
